language: go
go:
  - "1.11.x"
  - "tip"
os:
  - linux
  - osx
  - windows
env:
  - GO111MODULE=on
# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true
sudo: false
matrix:
  allow_failures:
    - go: "tip"
script:
  - ./ci/validate-gofmt.sh
  - go get -u golang.org/x/lint/golint
  - ./ci/validate-lint.sh
  - go test -race -v ./...

